<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYa3xgoe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYa3xgoe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYa3xgoe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYa3xgoe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYa3xgoe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ya3xgoe',
    'container.build_id' => 'c25bc5fe',
    'container.build_time' => 1590073099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYa3xgoe');
