<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4bOnqs6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4bOnqs6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4bOnqs6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4bOnqs6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4bOnqs6\App_KernelDevDebugContainer([
    'container.build_hash' => '4bOnqs6',
    'container.build_id' => 'b92a4658',
    'container.build_time' => 1590243169,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4bOnqs6');
